package:
  name: proteinsolver
  version: 0.1.23

source:
  path: ../../

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    - ruamel.yaml >=0.16.0
    - brotlipy
    - numpy
    - scipy
    - pandas
    - numba
    - kmbio >=2.0.19
    - kmtools >=0.2.3
    - pytorch >=1.4
    # - torch-geometric

test:
  imports:
    - proteinsolver

about:
  home: https://gitlab.com/ostrokach/proteinsolver
  license: MIT License
  summary: "Learn to solve constraint satisfaction problems (CSPs) from data."
